red_list = [
    "planning to kill myself",
    "going to end my life", 
    "want to commit suicide",
    "thinking about suicide",
    "considering ending my life",
    "planning my own death",
    "ready to die by suicide",
    "preparing to kill myself",
    "researching suicide methods",
    "wrote my suicide note",
    "saying final goodbye",
    "this is my last message",
    "going to take my own life",
    "want to die by my own hand",
    "planning to harm myself fatally",
    "contemplating ending everything",
    "ready to leave this world",
    "going to make the pain stop forever",
    "planning to not wake up",
    "going to join the deceased",
    "want to kill someone",
    "planning to hurt people",
    "going to shoot people", 
    "thinking about killing others",
    "want to cause harm to others",
    "planning violence against others",
    "going to make them pay with violence",
    "considering hurting innocent people",
    "wanting to harm my family",
    "planning to bring weapon to school",
    "thinking about mass violence"
]

yellow_list = [
    "feel hopeless",
    "worthless",
    "want to disappear",
    "tired of living", 
    "can't go on",
    "everything is pointless",
    "world better without me",
    "feel like a burden",
    "cutting myself",
    "self harm",
    "hurting myself",
    "want to hurt myself",
    "burning myself",
    "hitting myself",
    "feel unsafe",
    "someone hurts me",
    "being abused",
    "afraid to go home",
    "being threatened",
    "in danger",
    "completely alone",
    "nobody cares",
    "no friends",
    "isolated",
    "abandoned",
    "drinking too much",
    "using drugs to cope",
    "addicted",
    "need pills to sleep",
    "panic attacks",
    "can't breathe",
    "losing my mind",
    "going crazy",
    "breaking down",
    "overwhelmed",
    "can't handle this"
]

block_list = [
    "kms",
    "kill myself", 
    "suicide",
    "suicidal",
    "end my life",
    "take my life",
    "want to die"
]