red_list = [
    # Direct Suicide Ideation & Plans
    "kill myself", "kms", "end my life", "take my own life", "want to die",
    "don't want to live anymore", "want to disappear forever", "ready to end it all",
    "suicide", "suicidal", "commit suicide", "committing suicide", "final exit",
    "no reason to live", "goodbye cruel world", "can't go on", "it's over for me",
    "there's no other way out", "maybe the world would be better without me",
    "i've written goodbye letters", "i'm planning to end it all tonight",
    "i'm tired of being alive", "i just want it to stop forever",
    "i've made peace with not waking up", "i already said goodbye to my friends",
    "i want to jump and never come back", "there's nothing left for me here",
    "this is my last message", "i just want it to be over", "i'm ready to vanish forever",
    "please don't try to stop me this time", "how to die peacefully at home",
    "i'm looking for ways to not wake up", "it's my final night", "tonight is the night",
    "i can't take another day", "kill me", "please kill me", "someone end my life",
    "i want someone to kill me", "wishing for death", "if i could just not wake up",
    "the only solution is to die", "thinking about ending things", "my time is up",
    "i've decided to leave this world", "the final solution", "i've had enough of living",
    "ready for the long sleep", "i'm done with life", "there's no point in living",
    "contemplating suicide", "serious about ending it", "my death is the only answer",
    "i feel like my only option is to die", "i'm going to take my life", "i'm ending my pain",
    "i've chosen my path and it ends here", "i'm going to be with the stars tonight",
    "the pain will be over soon", "i'm saying my final goodbyes", "life isn't worth it",
    "i'm preparing for the end", "i have a plan to end my life", "i know how i'll do it",
    "the decision has been made", "i'm just waiting for the right moment", "it's all planned out",
    "i've got everything ready", "soon it will all be over", "i can't live like this",
    "the world is better off without me", "i'm a ghost already", "i feel dead inside",
    "my soul is already gone", "i'm just a shell", "there's nothing left of me",
    "i'm already dead", "i'm just waiting for my body to catch up", "i'm a walking corpse",
    "i'm a shadow of myself", "i'm not really here anymore", "i've lost myself completely",
    "there's no coming back from this", "i'm beyond help", "it's too late for me",
    "i'm a lost cause", "i'm a failure", "i'm a disgrace", "i'm worthless",
    
    # Self-Harm Methods & Actions
    "overdose", "pills and alcohol", "hanging myself", "jumping off a bridge",
    "slitting my wrists", "got a gun", "how to tie a noose", "razor blade",
    "how to die painlessly", "how many pills does it take to die", "bleeding out",
    "carbon monoxide poisoning", "drowning myself", "electrocution", "jumping in front of a train",
    "playing with a loaded gun", "driving off a cliff", "drinking poison", "self-immolation",
    "i bought a rope", "i have the pills", "the gun is loaded", "i'm at the edge",
    "standing on the ledge", "the water is cold", "the garage is sealed", "i've locked the door",
    "no one can stop me now", "this is happening", "i'm going through with it", "i'm doing it",
    "here i go", "this is the end", "it's time", "now or never", "the final act",
    "one last breath", "the final step", "the final cut", "the final pill", "the final jump",

    # Direct Threats & Violence Towards Others
    "i will kill you", "i will kill him", "i will kill her", "i am going to kill them",
    "i want to murder someone", "i will murder you", "planning to kill",
    "i kill you", "i kill him", "i kill her", "going to hurt someone",
    "want to hurt people", "everyone deserves to die", "i'm going to shoot",
    "bring a weapon to school", "hurt my family", "i'm going to make them pay",
    "they will all be sorry", "i'll take them with me", "they're going to die",
    "i'll make them suffer", "i want to see them bleed", "i'm going to hurt them badly",
    "i'm going to end them", "i'll get my revenge", "i'm going on a rampage",
    "i'm going to snap", "i'm about to explode", "i'm losing control", "i'm a ticking time bomb",
    "i'm dangerous", "i'm a threat", "i'm a monster", "i'm evil", "i have no remorse",
    "i don't care who gets hurt", "i want to watch the world burn", "i enjoy hurting others",
    "i'm going to make a statement", "they will remember my name", "i will not be forgotten",
    "i'm going to be infamous", "i'll be on the news", "i'm going to make history",
    "i'm the angel of death", "i'm the grim reaper", "i'm the devil", "i'm a demon",
    "i'm a psychopath", "i'm a sociopath", "i'm a narcissist", "i'm a sadist",
    "i'm a masochist", "i'm a killer", "i'm a murderer", "i'm a criminal",
    "i'm a villain", "i'm the bad guy", "i'm the hero of my own story", "i'm the protagonist",
    "i'm the antagonist", "i'm the main character", "i'm the one in control", "i'm the one who decides",
    "i'm the judge, jury, and executioner", "i'm god", "i'm a god", "i'm immortal",
    "i'm invincible", "i'm untouchable", "i'm unstoppable", "i'm inevitable",
    "i am the danger", "i am the one who knocks", "i am the storm", "i am the apocalypse",
    "i am the end", "i am death", "i am chaos", "i am destruction", "i am war",
    "i am vengeance", "i am justice", "i am the law", "i am the truth", "i am the way",
    "i am the light", "i am the darkness", "i am the alpha and the omega", "i am everything",
    "i am nothing", "i am nobody", "i am everybody", "i am you", "i am me",
    
]

yellow_list = [
    # Depression & Hopelessness
    "hopeless", "worthless", "crippling depression", "can't get out of bed",
    "numb inside", "everything is pointless", "unbearable pain", "crushing weight",
    "drowning", "empty inside", "feel nothing", "lost all motivation",
    "can't see the point", "what's the use", "nothing brings joy",
    "feel like giving up", "too tired to try", "exhausted from living",
    "i feel invisible", "i'm drowning and no one sees it", "i cry myself to sleep",
    "i can't eat or sleep anymore", "i'm exhausted from pretending i'm okay",
    "everything feels so heavy", "my brain won't stop screaming", "i feel like a burden",
    "i just want to sleep forever", "no one would notice if i vanished", "i'm scared of myself",
    "i keep messing everything up", "i'm not strong enough for this",
    "it's always dark inside my head", "i hate being alive",
    "i just want a break from existing", "i'm emotionally numb",
    "no one understands how broken i feel", "i keep hurting inside", "the sadness is overwhelming",
    "i'm sinking", "i'm falling apart", "i'm at the end of my rope", "i'm losing hope",
    "there's no light at the end of the tunnel", "i'm stuck in a black hole", "my world is crumbling",
    "i'm in a living hell", "i'm in agony", "i'm in despair", "i'm in turmoil",
    
    # Anxiety, Panic & Overwhelm
    "panic attack", "can't breathe", "hyperventilating", "feel like I'm dying",
    "losing my mind", "spiraling out of control", "overwhelmed",
    "everything is falling apart", "can't handle this", "breaking down",
    "having a breakdown", "losing control", "going crazy",
    "can't cope anymore", "too much pressure", "about to snap", "the anxiety is crippling",
    "my heart is racing", "i feel like i'm going to have a heart attack", "i'm shaking",
    "i'm sweating", "i'm dizzy", "i'm lightheaded", "i feel faint", "i'm going to pass out",
    "i'm having chest pains", "i can't think straight", "my mind is racing", "i'm on edge",
    
    # Non-Suicidal Self-Harm
    "self-harm", "cutting myself", "want to hurt myself", "hitting myself",
    "burning myself", "need to feel pain", "cutting again",
    "relapsed with cutting", "hurting myself helps", "physical pain helps",
    "scratching until I bleed", "pulling my hair out", "biting myself",
    "i deserve to be punished", "i need to feel something", "the pain makes me feel alive",
    "i want to see blood", "i like the scars", "the scars are a reminder", "i'm a cutter",
    
    # Safety Concerns & Abuse
    "I'm not safe", "scared for my life", "he hits me", "she abuses me",
    "being threatened", "in danger", "afraid to go home",
    "someone is hurting me", "being stalked", "threatened violence",
    "domestic violence", "being beaten", "sexual abuse",
    "afraid of my partner", "hiding bruises", "can't escape",
    "i'm being controlled", "i'm being manipulated", "i'm being gaslighted",
    "i'm being blackmailed", "i'm being extorted", "i'm being held against my will",
    "i'm a prisoner in my own home", "i'm a hostage", "i'm a victim", "i'm a survivor",
    
    # Isolation & Loneliness
    "completely alone", "no one cares", "nobody understands",
    "isolated from everyone", "feel disconnected", "no friends left",
    "abandoned by everyone", "talking to no one", "sitting alone",
    "eating alone every day", "spending days without talking",
    "haven't left the house", "avoiding everyone", "pushing people away",
    "i'm a loner", "i'm an outcast", "i'm a pariah", "i'm invisible",
    "i'm a ghost", "i'm a nobody", "i don't belong here", "i'm not wanted",
    
    # Substance Abuse
    "drinking too much", "using drugs to cope", "can't stop drinking",
    "need something to numb the pain", "addicted", "substance abuse",
    "drinking every day", "getting high to forget", "pills to sleep",
    "alcohol is my only friend", "drugs make it better", "need my fix",
    "i'm a drunk", "i'm an alcoholic", "i'm a drug addict", "i'm a junkie",
    
    # Eating Disorders
    "starving myself", "throwing up after eating", "obsessed with weight",
    "counting every calorie", "feel fat and disgusting", "binge eating",
    "purging", "anorexic", "bulimic", "hate my body",
    "food is the enemy", "weighing myself constantly", "diet pills",
    
    # Trauma & PTSD
    "flashbacks", "nightmares every night", "can't forget what happened",
    "ptsd", "triggered", "dissociating", "feeling detached",
    "not in my body", "watching myself from outside", "memory gaps",
    "intrusive thoughts", "can't stop remembering", "feel like it's happening again",
    
    # Severe Stress (Work, School, Financial)
    "failing everything", "can't concentrate", "falling behind",
    "overwhelming workload", "academic pressure", "job stress",
    "performance anxiety", "imposter syndrome", "burnout",
    "can't meet expectations", "disappointing everyone", "career falling apart",
    "broke", "can't pay bills", "losing my home", "bankruptcy",
    "financial ruin", "drowning in debt", "no money for food",
    "eviction notice", "car repossessed", "credit ruined",
    
    # Relationship Distress
    "relationship falling apart", "partner left me", "going through divorce",
    "lost my best friend", "family doesn't understand", "rejected",
    "heartbroken", "betrayed", "cheated on", "abandoned",
    "can't trust anyone", "everyone leaves", "scared of commitment",
    
]

block_list = [
    "kill myself", 
    "kms",
    "suicide",
    "suicidal",
    "kill me",
    "kill",
    "murder",
    "shoot",
    "stab",
    "hang",
    "overdose",
]
